stages:
  - lint
  - test

prettier:
  stage: lint
  image: node:25-alpine
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install
  script:
    - npm ci
    - npx prettier --check .
  artifacts:
    when: always
    reports:
      junit: gl-prettier-report.json
    paths:
      - ./reports/gl-prettier-report.json
    expire_in: 1 week
  allow_failure: false

test:
  stage: test
  image: node:25-alpine
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install
  script:
    - npm test
